-- Migración: Añadir sistema de etiquetas a productos
-- Fecha: 2025-11-30
-- Descripción: Crea tablas para etiquetas y su relación muchos-a-muchos con productos

-- Crear tabla de etiquetas
create table public.tag (
  id bigint generated by default as identity not null,
  name character varying not null,
  slug character varying not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  constraint tag_pkey primary key (id),
  constraint tag_name_unique unique (name),
  constraint tag_slug_unique unique (slug)
) TABLESPACE pg_default;

-- Índices para mejorar el rendimiento
create index tag_slug_idx on public.tag(slug);
create index tag_name_idx on public.tag(name);

-- Comentarios para tabla tag
COMMENT ON TABLE public.tag IS 'Etiquetas que se pueden asociar a productos';
COMMENT ON COLUMN public.tag.name IS 'Nombre de la etiqueta';
COMMENT ON COLUMN public.tag.slug IS 'Slug para URLs';

-- Crear tabla intermedia para la relación muchos-a-muchos
create table public.product_tag (
  product_id bigint not null,
  tag_id bigint not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  constraint product_tag_pkey primary key (product_id, tag_id),
  constraint product_tag_product_id_fkey foreign key (product_id) references product (id) on update CASCADE on delete CASCADE,
  constraint product_tag_tag_id_fkey foreign key (tag_id) references tag (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

-- Índices para mejorar el rendimiento de las consultas
create index product_tag_product_id_idx on public.product_tag(product_id);
create index product_tag_tag_id_idx on public.product_tag(tag_id);

-- Comentarios para tabla product_tag
COMMENT ON TABLE public.product_tag IS 'Relación muchos-a-muchos entre productos y etiquetas';
COMMENT ON COLUMN public.product_tag.product_id IS 'ID del producto';
COMMENT ON COLUMN public.product_tag.tag_id IS 'ID de la etiqueta';

