create table public.additional_product_images (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  updated_at timestamp without time zone not null default (now() AT TIME ZONE 'utc'::text),
  product_id bigint not null,
  image_url character varying not null,
  alt_text character varying null,
  caption character varying null,
  display_order integer not null,
  constraint additional_product_images_pkey primary key (id),
  constraint additional_product_images_display_order_key unique (display_order),
  constraint additional_product_images_product_id_fkey foreign KEY (product_id) references product (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;