create table public.category (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  updated_at timestamp without time zone not null default (now() AT TIME ZONE 'utc'::text),
  name character varying not null,
  image_url character varying null,
  slug character varying null,
  constraint category_pkey primary key (id)
) TABLESPACE pg_default;