create table public.product (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  updated_at timestamp without time zone null default (now() AT TIME ZONE 'utc'::text),
  title character varying null,
  description text null,
  price real null,
  category_id bigint not null,
  main_image_url character varying null,
  slug character varying not null,
  constraint producto_pkey primary key (id),
  constraint producto_category_id_fkey foreign KEY (category_id) references category (id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;