-- Tabla de etiquetas
create table public.tag (
  id bigint generated by default as identity not null,
  name character varying not null,
  slug character varying not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  constraint tag_pkey primary key (id),
  constraint tag_name_unique unique (name),
  constraint tag_slug_unique unique (slug)
) TABLESPACE pg_default;

-- Índices para mejorar el rendimiento
create index tag_slug_idx on public.tag(slug);
create index tag_name_idx on public.tag(name);

-- Comentarios
COMMENT ON TABLE public.tag IS 'Etiquetas que se pueden asociar a productos';
COMMENT ON COLUMN public.tag.name IS 'Nombre de la etiqueta';
COMMENT ON COLUMN public.tag.slug IS 'Slug para URLs';

